# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-21 09:40
from __future__ import unicode_literals

import DjangoUeditor.models
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ic_shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('sex', models.CharField(choices=[('未知', '未知'), ('男', '男'), ('女', '女')], default='未知', max_length=50, null=True, verbose_name='性别')),
                ('birthDate', models.DateField(blank=True, default='1970-01-01', null=True, verbose_name='出生日期')),
                ('nickName', models.CharField(default='', max_length=50, null=True, verbose_name='昵称')),
                ('mobile', models.CharField(error_messages={'unique': '该手机号已被注册.'}, help_text='手机账号', max_length=255, verbose_name='手机账号')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=ic_shop.models.Profile.get_avatar_path)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AreasInfo',
            fields=[
                ('id', models.CharField(default='0', max_length=50, primary_key=True, serialize=False, verbose_name='区域编号')),
                ('name', models.CharField(default='', max_length=50, null=True, verbose_name='区域名称')),
                ('areaLevel', models.CharField(default='', max_length=50, null=True, verbose_name='区域层级')),
                ('parent_id', models.CharField(default='', max_length=50, null=True, verbose_name='区域母编号')),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='默认', error_messages={'unique': '该品牌已经存在'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=255, unique=True, verbose_name='标签名称')),
                ('status', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)], verbose_name='0- 未激活, 1 - 激活, 2- 过期')),
                ('description', models.TextField(blank=True, max_length=1024, verbose_name='描述')),
                ('entry_date', models.DateTimeField(auto_now_add=True, verbose_name='入库时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '商品品牌',
                'verbose_name_plural': '商品品牌',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=1024, null=True, verbose_name='标题')),
                ('description', models.CharField(blank=True, max_length=1024, verbose_name='描述')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '商品评论',
                'verbose_name_plural': '商品评论',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, unique=True, verbose_name='公司名称')),
                ('address', models.CharField(default='', max_length=100, null=True, verbose_name='公司地址')),
                ('mobile', models.CharField(default='', max_length=100, null=True, verbose_name='公司电话')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=ic_shop.models.Company.get_logo_path)),
                ('describe', models.CharField(default='', max_length=500, null=True, verbose_name='公司简介')),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='发表时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('offic_acc_url', models.CharField(default='', max_length=100, null=True, verbose_name='公众号URL')),
                ('offic_acc_content', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='公众号描述')),
                ('ali_appId', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='支付宝-公司支付APPID')),
                ('ali_publicKey', models.TextField(blank=True, null=True, verbose_name='支付宝-支付宝公钥')),
                ('ali_privateKey', models.TextField(blank=True, null=True, verbose_name='支付宝-应用私钥')),
                ('ali_notifyUrl', models.CharField(blank=True, max_length=255, null=True, verbose_name='支付宝-支付通知url')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader', to=settings.AUTH_USER_MODEL, verbose_name='公司负责人')),
            ],
            options={
                'verbose_name': '公司',
                'verbose_name_plural': '公司',
            },
        ),
        migrations.CreateModel(
            name='CompanyDeviceUpdatePackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.FloatField(blank=True, default='1.0', null=True, verbose_name='版本号')),
                ('file', models.FileField(blank=True, null=True, upload_to=ic_shop.models.CompanyDeviceUpdatePackage.get_package_path, verbose_name='更新包')),
                ('description', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='介绍')),
                ('entry_date', models.DateTimeField(auto_now_add=True, verbose_name='入库时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ic_shop.Company', verbose_name='所属公司')),
            ],
            options={
                'verbose_name': '公司设备升级包',
                'verbose_name_plural': '公司设备升级包',
            },
        ),
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(0)], verbose_name=' 0：未知，1：厂家，2：经销商, 3: 总公司 ')),
                ('name', models.CharField(default='', max_length=20, null=True, verbose_name='类型名称')),
                ('describe', models.CharField(default='', max_length=200, null=True, verbose_name='类型描述')),
            ],
            options={
                'verbose_name': '公司类型',
                'verbose_name_plural': '公司类型',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='小卧智能冰糕机2型', max_length=1024, null=True, verbose_name='设备名称')),
                ('img', models.FileField(blank=True, null=True, upload_to=ic_shop.models.Device.get_device_path)),
                ('description', models.TextField(blank=True, default='', max_length=1024, verbose_name='描述')),
                ('deviceSn', models.CharField(error_messages={'unique': '设备SN已经存在'}, help_text='设备sn', max_length=50, unique=True, verbose_name='设备SN')),
                ('appVersion', models.CharField(default='', max_length=50, null=True, verbose_name='app版本')),
                ('androidVersion', models.CharField(default='', max_length=50, null=True, verbose_name='安卓系统版本')),
                ('deviceVersion', models.CharField(default='', max_length=50, null=True, verbose_name='下位机固件版本')),
                ('settingTemperature', models.CharField(default='-18', max_length=50, null=True, verbose_name='设定温度')),
                ('temperature', models.CharField(default='-18', max_length=50, null=True, verbose_name='实时温度')),
                ('temperatureThreshold', models.CharField(blank=True, default='10', help_text='最高报警温度阈值', max_length=50, null=True, verbose_name='最高报警温度阈值')),
                ('entry_date', models.DateTimeField(auto_now_add=True, verbose_name='入库时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
                'permissions': (('view_device', 'View device'),),
            },
        ),
        migrations.CreateModel(
            name='DeviceAds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=1024, null=True, verbose_name='标题')),
                ('type', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)], verbose_name='类型,0-最新动态,1-产品攻略,2-专业技能')),
                ('description', models.TextField(blank=True, default='', max_length=1024, verbose_name='描述')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='内容')),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='上传时间')),
                ('refresh_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('read_count', models.CharField(default='0', max_length=30, verbose_name='阅读数')),
                ('like_count', models.CharField(default='0', max_length=30, verbose_name='点赞数')),
            ],
            options={
                'verbose_name': '资讯广告',
                'verbose_name_plural': '资讯广告',
            },
        ),
        migrations.CreateModel(
            name='DeviceLocationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='经度')),
                ('latitude', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='纬度')),
                ('provinceKey', models.CharField(default='', max_length=50, null=True, verbose_name='省份编码')),
                ('provinceName', models.CharField(default='', max_length=50, null=True, verbose_name='省份')),
                ('cityKey', models.CharField(default='', max_length=50, null=True, verbose_name='县市编码')),
                ('cityName', models.CharField(default='', max_length=50, null=True, verbose_name='县市')),
                ('regionKey', models.CharField(default='', max_length=50, null=True, verbose_name='区编码')),
                ('regionName', models.CharField(default='', max_length=50, null=True, verbose_name='区')),
                ('addressDetail', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='地址详情')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '设备历史地址',
                'verbose_name_plural': '设备历史地址',
            },
        ),
        migrations.CreateModel(
            name='DeviceOperationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceSn', models.CharField(max_length=255, verbose_name='所属设备')),
                ('deviceVerifyCode', models.CharField(default='', max_length=200, null=True, verbose_name='设备操作校验码')),
                ('codeUpdateTime', models.CharField(default='', max_length=200, null=True, verbose_name='验证码更新时间戳')),
                ('timeExpired', models.CharField(default='2', max_length=1024, null=True, verbose_name='检验码过期时间间隔')),
                ('upload_time', models.DateTimeField(auto_now=True, null=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '设备操作校验',
                'verbose_name_plural': '商品种类',
            },
        ),
        migrations.CreateModel(
            name='DeviceSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slotNum', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(1)], verbose_name='设备通道序号(1-30)')),
                ('status', models.IntegerField(default=1, help_text='-0- 未激活, 1 - 激活, 2 - 过期, 3 - 已被使用', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='机器状态')),
                ('faultCode', models.CharField(blank=True, default=-1, help_text='1:正常 , 2：送料电机故障，3：顶出的电机故障，4、电动门电磁阀故障', max_length=50, null=True, verbose_name='故障状态')),
                ('max_capacity', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(1)], verbose_name='设备通道容量(1-30)')),
            ],
            options={
                'verbose_name': '设备通道',
                'verbose_name_plural': '设备通道',
                'default_related_name': 'deviceSlot',
            },
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1024, null=True, verbose_name='设备型号名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '设备类型',
                'verbose_name_plural': '设备类型',
            },
        ),
        migrations.CreateModel(
            name='ImageUploader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='upload')),
                ('upload_time', models.DateTimeField(auto_now=True, null=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '商品图片',
                'verbose_name_plural': '商品图片',
            },
        ),
        migrations.CreateModel(
            name='ItemOrder',
            fields=[
                ('orderNum', models.BigIntegerField(error_messages={'unique': '订单号重复'}, primary_key=True, serialize=False, verbose_name='订单号')),
                ('orderTitle', models.CharField(error_messages={'null': '需要提供商品名称或者相关标题'}, max_length=255, verbose_name='订单标题')),
                ('totalCount', models.IntegerField(error_messages={'null': '购买商品总数'}, verbose_name='购买商品总数')),
                ('actualTotalCount', models.IntegerField(default=0, error_messages={'null': '实际出货商品总数'}, verbose_name='实际出货数量')),
                ('totalPrize', models.FloatField(error_messages={'null': '需要提供商品总价'}, verbose_name='总价')),
                ('deviceSlot_id', models.CharField(error_messages={'null': '需要提供所属通道ID'}, help_text='deviceSlot_id', max_length=255, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('update_timestamp', models.BigIntegerField(verbose_name='操作时间戳')),
            ],
            options={
                'verbose_name': '商品订单',
                'verbose_name_plural': '商品订单',
            },
        ),
        migrations.CreateModel(
            name='ProfileAvatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='upload/avatar')),
                ('upload_time', models.DateTimeField(auto_now=True, null=True, verbose_name='上传时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '头像',
                'verbose_name_plural': '头像',
            },
        ),
        migrations.CreateModel(
            name='ProfileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='用户类型')),
                ('description', models.CharField(default='', max_length=1024, verbose_name='描述')),
            ],
            options={
                'verbose_name': '用户类型',
                'verbose_name_plural': '用户类型',
            },
        ),
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='默认', error_messages={'unique': '该商品名称已经存在'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=255, unique=True, verbose_name='商品名称')),
                ('description', models.CharField(blank=True, max_length=1024, verbose_name='描述')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='内容')),
                ('prize', models.FloatField(error_messages={'unique': '价格不能低于0'}, validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(0)], verbose_name='价格')),
                ('originalPrize', models.FloatField(help_text='出厂价格', null=True, validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(0)], verbose_name='出厂价格')),
                ('status', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)], verbose_name='-0- 未激活, 1 - 激活, 2 - 过期')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='上架时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('img', models.FileField(blank=True, null=True, upload_to=ic_shop.models.ShopItem.get_shopItem_path)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ic_shop.Brand', verbose_name='所属品牌')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
        migrations.CreateModel(
            name='ShopItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1024, null=True, verbose_name='商品种类名称')),
                ('upload_time', models.DateTimeField(auto_now=True, null=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '商品种类',
                'verbose_name_plural': '商品种类',
            },
        ),
        migrations.CreateModel(
            name='ShopItemStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentStorage', models.CharField(max_length=50, null=True, verbose_name='当前存货量')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('deviceSlot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deviceSlots', to='ic_shop.DeviceSlot', verbose_name='所属通道')),
                ('shopItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopItems', to='ic_shop.ShopItem', verbose_name='冰糕')),
            ],
            options={
                'verbose_name': '设备商品存货',
                'verbose_name_plural': '设备商品存货',
            },
        ),
        migrations.CreateModel(
            name='ShopItemStorageHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50, null=True, verbose_name='所属设备id')),
                ('pre_shopItem_id', models.CharField(max_length=50, null=True, verbose_name='之前商品ID')),
                ('user_id', models.CharField(max_length=50, null=True, verbose_name='操作员ID')),
                ('pre_currentStorage', models.CharField(max_length=50, null=True, verbose_name='更新之前存货量')),
                ('currentStorage', models.CharField(max_length=50, null=True, verbose_name='当前存货量')),
                ('update_timestamp', models.BigIntegerField(default=0, verbose_name='操作时间戳')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('deviceSlot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ic_shop.DeviceSlot', verbose_name='所属通道')),
                ('shopItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ic_shop.ShopItem', verbose_name='冰糕')),
            ],
            options={
                'verbose_name': '设备商品存货历史记录',
                'verbose_name_plural': '设备商品存货历史记录',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'unique': 'A title with that tag already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, verbose_name='标签名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceLocation',
            fields=[
                ('longitude', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='经度')),
                ('latitude', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='纬度')),
                ('provinceKey', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='省份编码')),
                ('provinceName', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='省份')),
                ('cityKey', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='县市编码')),
                ('cityName', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='县市')),
                ('regionKey', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='区编码')),
                ('regionName', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='区')),
                ('addressDetail', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='地址详情')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ic_shop.Device', verbose_name='所属设备')),
            ],
            options={
                'verbose_name': '设备地址',
                'verbose_name_plural': '设备地址',
            },
        ),
        migrations.CreateModel(
            name='DeviceMacStatus',
            fields=[
                ('status', models.IntegerField(default=1, help_text='0：未激活状态，1：正常运作，2、用户购买中，3、补货中，4：离线状态，5：报废，', validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='0：未激活状态，1：正常运作，2、用户购买中，3、补货中，4：离线状态，5：报废，')),
                ('faultStatus', models.IntegerField(default='1', help_text='1-:正常, 2：通道电机故障, 3：横送系统故障, 4：升降系统故障', validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)], verbose_name='1-:正常, 2：通道电机故障, 3：横送系统故障, 4：升降系统故障')),
                ('temperatureStatus', models.IntegerField(default='1', help_text='(高温状态) 0-异常 1-:正常', validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)], verbose_name='(高温状态) 0-异常 1-:正常')),
                ('republishStatus', models.IntegerField(default='1', help_text='设备补货状态码，0：无需补货，1：待补货，2：亟待补货', validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)], verbose_name='设备补货状态码，0：无需补货，1：待补货，2：亟待补货')),
                ('device', models.OneToOneField(help_text='device_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ic_shop.Device', verbose_name='所属设备')),
            ],
            options={
                'verbose_name': '设备状态',
                'verbose_name_plural': '设备状态',
            },
        ),
        migrations.CreateModel(
            name='ItemOrderStatus',
            fields=[
                ('orderStatus', models.IntegerField(default=0, help_text='0- 等待支付中, 1 - 已支付, 2 - 已取消, 3 - 未付款交易超时关闭，或支付完成后全额退款, 4 - 退款中 5- 该订单未被扫描 6- 交易结束，不可退款  ', null=True, validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(0)], verbose_name='0- 等待支付中, 1 - 已支付, 2 - 已取消, 3 - 未付款交易超时关闭，或支付完成后全额退款, 4 - 退款中 5- 该订单未被扫描 6- 交易结束，不可退款  ')),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='发表时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('update_timestamp', models.BigIntegerField(null=True, verbose_name='操作时间戳')),
                ('buyer_user_id', models.CharField(blank=True, help_text='支付宝用户ID, 默认生成, 无需填写', max_length=255, null=True)),
                ('buyer_logon_id', models.CharField(blank=True, help_text='支付宝用户登录ID, 默认生成, 无需填写', max_length=255, null=True)),
                ('company_id', models.IntegerField(blank=True, help_text='公司ID', null=True)),
                ('orderNum', models.OneToOneField(default=1, error_messages={'null': '需要提供该订单的商品ID'}, help_text='itemOrder_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ic_shop.ItemOrder', verbose_name='所属订单')),
                ('orderCompleteStatus', models.IntegerField(default=0, help_text='0 - 未出货, 1 -已出货  2-部分出货', null=True, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)], verbose_name='0 - 未出货 1 - 已出货  2-部分出货')),
            ],
            options={
                'verbose_name': '订单状态',
                'verbose_name_plural': '订单状态',
            },
        ),
        migrations.AddField(
            model_name='userdevice',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='ic_shop.Device', verbose_name='设备'),
        ),
        migrations.AddField(
            model_name='userdevice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ic_shop.ShopItemCategory', verbose_name='商品种类'),
        ),
        migrations.AddField(
            model_name='itemorder',
            name='company',
            field=models.ForeignKey(error_messages={'null': '需要提供公司ID'}, help_text='company_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='ic_shop.Company', verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='itemorder',
            name='device',
            field=models.ForeignKey(error_messages={'null': '需要提供所属设备ID'}, help_text='device_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='ic_shop.Device'),
        ),
        migrations.AddField(
            model_name='itemorder',
            name='shopItem',
            field=models.ForeignKey(error_messages={'null': '需要提供该订单的商品ID'}, help_text='shopItem_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='ic_shop.ShopItem', verbose_name='所属商品'),
        ),
        migrations.AddField(
            model_name='imageuploader',
            name='shopItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ic_shop.ShopItem'),
        ),
        migrations.AddField(
            model_name='deviceslot',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deviceSlot', to='ic_shop.Device', verbose_name='设备'),
        ),
        migrations.AddField(
            model_name='deviceslot',
            name='shopItem',
            field=models.ManyToManyField(related_name='deviceSlot', through='ic_shop.ShopItemStorage', to='ic_shop.ShopItem', verbose_name='冰糕'),
        ),
        migrations.AlterUniqueTogether(
            name='deviceoperationcode',
            unique_together=set([('deviceSn', 'deviceVerifyCode')]),
        ),
        migrations.AddField(
            model_name='devicelocationhistory',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ic_shop.Device', verbose_name='所属设备'),
        ),
        migrations.AddField(
            model_name='device',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ic_shop.Company', verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='device',
            name='deviceType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ic_shop.DeviceType', verbose_name='所属设备类型'),
        ),
        migrations.AddField(
            model_name='device',
            name='operator',
            field=models.ManyToManyField(blank=True, through='ic_shop.UserDevice', to=settings.AUTH_USER_MODEL, verbose_name='设备'),
        ),
        migrations.AddField(
            model_name='company',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ic_shop.CompanyType', verbose_name='公司类型'),
        ),
        migrations.AddField(
            model_name='comment',
            name='shopItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ic_shop.ShopItem', verbose_name='所属商品'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ic_shop.Company', verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='profile',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='profile',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上级用户'),
        ),
        migrations.AddField(
            model_name='profile',
            name='userType',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='ic_shop.ProfileType', verbose_name='用户类型'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AlterUniqueTogether(
            name='userdevice',
            unique_together=set([('device', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='deviceslot',
            unique_together=set([('device', 'slotNum')]),
        ),
    ]
