# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-21 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import ic_shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('ic_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceads',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=ic_shop.models.DeviceAds.get_thumbnail_path),
        ),
        migrations.AlterField(
            model_name='deviceads',
            name='title',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='标题'),
        ),
    ]
