# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-24 11:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ic_shop', '0003_deviceads_top_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopitem',
            name='prize',
        ),
        migrations.AddField(
            model_name='shopitem',
            name='discount',
            field=models.IntegerField(default=9, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='折扣,1-10'),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='new_status',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)], verbose_name='是否新品,0-否,1-是'),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='original_prize',
            field=models.FloatField(default=0, error_messages={'unique': '价格不能低于0'}, validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(0)], verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='description',
            field=models.CharField(blank=True, max_length=512, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='描述'),
        ),
    ]
