# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-24 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ic_shop', '0004_auto_20191024_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopitem',
            old_name='original_prize',
            new_name='market_prize',
        ),
    ]
