# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-25 14:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ic_shop', '0005_auto_20191024_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopitem',
            old_name='originalPrize',
            new_name='original_prize',
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='market_prize',
            field=models.FloatField(default=0, error_messages={'unique': '价格不能低于0'}, validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(0)], verbose_name='市场价格'),
        ),
    ]
