# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-29 15:46
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ic_shop', '0007_auto_20191029_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='kind_of_people',
            field=models.CharField(default='', max_length=30, null=True, verbose_name='适用人群, 0-儿童, 1-成人, 2-老人, 3-孕妇'),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='sex',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)], verbose_name='适用性别, 0-女, 1-男'),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='skin_type',
            field=models.CharField(default='', max_length=30, null=True, verbose_name='皮肤类型, 0-干性皮肤, 1-油性皮肤, 2-中性皮肤, 3-混合型皮肤'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='effect',
            field=models.CharField(default='', max_length=30, null=True, verbose_name='产品功效, 0-祛斑, 1-防嗮, 2-收缩毛孔, 3-补水, 4-祛痘, 5-修复, 6-抗氧化, 7-去皱淡纹'),
        ),
    ]
