# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-08 11:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import ic_shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('ic_shop', '0008_auto_20191029_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('未知', '未知'), ('男', '男'), ('女', '女')], default='未知', max_length=50, null=True, verbose_name='性别')),
                ('birthDate', models.DateField(blank=True, default='1970-01-01', null=True, verbose_name='出生日期')),
                ('nickName', models.CharField(default='', max_length=50, null=True, verbose_name='昵称')),
                ('cityKey', models.CharField(default='', max_length=50, null=True, verbose_name='县市编码')),
                ('cityName', models.CharField(default='', max_length=50, null=True, verbose_name='县市')),
                ('addressDetail', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='地址详情')),
                ('mail', models.CharField(blank=True, default='', help_text='电子邮箱', max_length=255, null=True, verbose_name='邮箱')),
                ('mobile', models.CharField(error_messages={'unique': '该手机号已被注册.'}, help_text='手机账号', max_length=255, verbose_name='手机账号')),
                ('isMarry', models.IntegerField(default=2, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)], verbose_name='是否结婚,1 - 是, 0 - 否, 2 - 未知')),
                ('isProcreate', models.IntegerField(default=2, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)], verbose_name='是否生育, 2 - 未知, 0 - 否, 1 - 是')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=ic_shop.models.Customer.get_avatar_path)),
                ('jobName', models.CharField(default='', max_length=50, null=True, verbose_name='昵称')),
                ('jobKey', models.CharField(default='', max_length=50, null=True, verbose_name='县市编码')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
            },
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='sex',
            field=models.CharField(choices=[('通用', '通用'), ('男', '男'), ('女', '女')], default='通用', max_length=50, null=True, verbose_name='适合性别'),
        ),
    ]
