# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-11 13:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ic_shop', '0009_auto_20191108_1157'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deviceslot',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='deviceslot',
            name='device',
        ),
        migrations.RemoveField(
            model_name='deviceslot',
            name='shopItem',
        ),
        migrations.RemoveField(
            model_name='shopitemstorage',
            name='deviceSlot',
        ),
        migrations.RemoveField(
            model_name='shopitemstorage',
            name='shopItem',
        ),
        migrations.RemoveField(
            model_name='shopitemstoragehistory',
            name='deviceSlot',
        ),
        migrations.RemoveField(
            model_name='shopitemstoragehistory',
            name='shopItem',
        ),
        migrations.DeleteModel(
            name='SkinType',
        ),
        migrations.RemoveField(
            model_name='devicemacstatus',
            name='republishStatus',
        ),
        migrations.RemoveField(
            model_name='devicemacstatus',
            name='temperatureStatus',
        ),
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)], verbose_name='0：未激活状态，1：正常运作，1：离线状态，3：报废'),
        ),
        migrations.AlterField(
            model_name='devicemacstatus',
            name='status',
            field=models.IntegerField(default=1, help_text='0：未激活状态，1：正常运作，2：离线状态，3：报废', validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(0)], verbose_name='0：未激活状态，1：正常运作，2：离线状态，3：报废'),
        ),
        migrations.DeleteModel(
            name='DeviceSlot',
        ),
        migrations.DeleteModel(
            name='ShopItemStorage',
        ),
        migrations.DeleteModel(
            name='ShopItemStorageHistory',
        ),
    ]
