# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-12 15:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ic_shop', '0010_auto_20191111_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportOverview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(default='0', max_length=20, null=True, verbose_name='综合得分')),
                ('skinType', models.IntegerField(default=-1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(-1)], verbose_name='皮肤类型, 0-干性皮肤, 1-油性皮肤, 2-中性皮肤, 3-混合型皮肤')),
                ('skinAge', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='皮肤年龄, 15-70')),
                ('opinion', models.CharField(default='', max_length=1024, null=True, verbose_name='理疗师综合意见')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ic_shop.Customer', verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '报告总览',
                'verbose_name_plural': '报告总览',
            },
        ),
        migrations.CreateModel(
            name='ReportOverviewShopItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overView', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overView', to='ic_shop.ReportOverview', verbose_name='报告总览')),
                ('shopItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoItem', to='ic_shop.ShopItem', verbose_name='美容商品')),
            ],
        ),
        migrations.AddField(
            model_name='reportoverview',
            name='shopItem',
            field=models.ManyToManyField(through='ic_shop.ReportOverviewShopItem', to='ic_shop.ShopItem', verbose_name='推荐美容产品'),
        ),
        migrations.AlterUniqueTogether(
            name='reportoverviewshopitem',
            unique_together=set([('overView', 'shopItem')]),
        ),
    ]
